# Generated by Django 5.1.1 on 2024-11-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.URLField(null=True),
        ),
    ]
