# Generated by Django 5.1.3 on 2024-11-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_remove_product_manufacturer_product_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyInstance',
            fields=[
                ('names', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phonenumber', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
